export const SITES_LIST_FOR_CUSTOMER_REQUEST = "SITES_LIST_FOR_CUSTOMER_REQUEST";
export const SITES_LIST_FOR_CUSTOMER_SUCCESS = "SITES_LIST_FOR_CUSTOMER_SUCCESS";
export const SITES_LIST_FOR_CUSTOMER_AFTER_SUCCESS = "SITES_LIST_FOR_CUSTOMER_AFTER_SUCCESS";
export const SITES_LIST_FOR_CUSTOMER_FAIL = "SITES_LIST_FOR_CUSTOMER_FAIL";

export const SITES_LIST_FOR_EACH_LOCATION_REQUEST = "SITES_LIST_FOR_EACH_LOCATION_REQUEST";
export const SITES_LIST_FOR_EACH_LOCATION_SUCCESS = "SITES_LIST_FOR_EACH_LOCATION_SUCCESS";
export const SITES_LIST_FOR_EACH_LOCATION_AFTER_SUCCESS = "SITES_LIST_FOR_EACH_LOCATION_AFTER_SUCCESS";
export const SITES_LIST_FOR_EACH_LOCATION_FAIL = "SITES_LIST_FOR_EACH_LOCATION_FAIL";

export const SITES_CREATE_REQUEST = "SITES_CREATE_REQUEST";
export const SITES_CREATE_SUCCESS = "SITES_CREATE_SUCCESS";
export const SITES_CREATE_AFTER_SUCCESS = "SITES_CREATE_AFTER_SUCCESS";
export const SITES_CREATE_FAIL = "SITES_CREATE_FAIL";

export const SITES_LIST_FOR_ADMIN_REQUEST = "SITES_LIST_FOR_ADMIN_REQUEST";
export const SITES_LIST_FOR_ADMIN_SUCCESS = "SITES_LIST_FOR_ADMIN_SUCCESS";
export const SITES_LIST_FOR_ADMIN_AFTER_SUCCESS = "SITES_LIST_FOR_ADMIN_AFTER_SUCCESS";
export const SITES_LIST_FOR_ADMIN_FAIL = "SITES_LIST_FOR_ADMIN_FAIL";

export const SITES_UPDATE_BY_ADMIN_REQUEST = "SITES_UPDATE_BY_ADMIN_REQUEST";
export const SITES_UPDATE_BY_ADMIN_SUCCESS = "SITES_UPDATE_BY_ADMIN_SUCCESS";
export const SITES_UPDATE_BY_ADMIN_AFTER_SUCCESS = "SITES_UPDATE_BY_ADMIN_AFTER_SUCCESS";
export const SITES_UPDATE_BY_ADMIN_FAIL = "SITES_UPDATE_BY_ADMIN_FAIL";

export const SITES_DELETE_BY_ADMIN_REQUEST = "SITES_DELETE_BY_ADMIN_REQUEST";
export const SITES_DELETE_BY_ADMIN_SUCCESS = "SITES_DELETE_BY_ADMIN_SUCCESS";
export const SITES_DELETE_BY_ADMIN_AFTER_SUCCESS = "SITES_DELETE_BY_ADMIN_AFTER_SUCCESS";
export const SITES_DELETE_BY_ADMIN_FAIL = "SITES_DELETE_BY_ADMIN_FAIL";
