export const RESERVATION_LIST_REQUEST = "RESERVATION_LIST_REQUEST";
export const RESERVATION_LIST_SUCCESS = "RESERVATION_LIST_SUCCESS";
export const RESERVATION_LIST_AFTER_SUCCESS = "RESERVATION_LIST_AFTER_SUCCESS";
export const RESERVATION_LIST_FAIL = "RESERVATION_LIST_FAIL";

export const ADMIN_RESERVATION_LIST_REQUEST = "ADMIN_RESERVATION_LIST_REQUEST";
export const ADMIN_RESERVATION_LIST_SUCCESS = "ADMIN_RESERVATION_LIST_SUCCESS";
export const ADMIN_RESERVATION_LIST_AFTER_SUCCESS = "ADMIN_RESERVATION_LIST_AFTER_SUCCESS";
export const ADMIN_RESERVATION_LIST_FAIL = "ADMIN_RESERVATION_LIST_FAIL";

export const RESERVATION_CREATE_REQUEST = "RESERVATION_CREATE_REQUEST";
export const RESERVATION_CREATE_SUCCESS = "RESERVATION_CREATE_SUCCESS";
export const RESERVATION_CREATE_AFTER_SUCCESS = "RESERVATION_CREATE_AFTER_SUCCESS";
export const RESERVATION_CREATE_FAIL = "RESERVATION_CREATE_FAIL";

export const RESERVATION_UPDATE_REQUEST = "RESERVATION_UPDATE_REQUEST";
export const RESERVATION_UPDATE_SUCCESS = "RESERVATION_UPDATE_SUCCESS";
export const RESERVATION_UPDATE_AFTER_SUCCESS = "RESERVATION_UPDATE_AFTER_SUCCESS";
export const RESERVATION_UPDATE_FAIL = "RESERVATION_UPDATE_FAIL";

export const RESERVATION_DELETE_REQUEST = "RESERVATION_DELETE_REQUEST";
export const RESERVATION_DELETE_SUCCESS = "RESERVATION_DELETE_SUCCESS";
export const RESERVATION_DELETE_AFTER_SUCCESS = "RESERVATION_DELETE_AFTER_SUCCESS";
export const RESERVATION_DELETE_FAIL = "RESERVATION_DELETE_FAIL";
