export const HOTEL_LIST_ADMIN_REQUEST = "HOTEL_LIST_ADMIN_REQUEST";
export const HOTEL_LIST_ADMIN_SUCCESS = "HOTEL_LIST_ADMIN_SUCCESS";
export const HOTEL_LIST_ADMIN_AFTER_SUCCESS = "HOTEL_LIST_ADMIN_AFTER_SUCCESS";
export const HOTEL_LIST_ADMIN_FAIL = "HOTEL_LIST_ADMIN_FAIL";

export const HOTEL_CREATE_ADMIN_REQUEST = "HOTEL_CREATE_ADMIN_REQUEST";
export const HOTEL_CREATE_ADMIN_SUCCESS = "HOTEL_CREATE_ADMIN_SUCCESS";
export const HOTEL_CREATE_ADMIN_AFTER_SUCCESS = "HOTEL_CREATE_ADMIN_AFTER_SUCCESS";
export const HOTEL_CREATE_ADMIN_FAIL = "HOTEL_CREATE_ADMIN_FAIL";

export const HOTEL_UPDATE_ADMIN_REQUEST = "HOTEL_UPDATE_ADMIN_REQUEST";
export const HOTEL_UPDATE_ADMIN_SUCCESS = "HOTEL_UPDATE_ADMIN_SUCCESS";
export const HOTEL_UPDATE_ADMIN_AFTER_SUCCESS = "HOTEL_UPDATE_ADMIN_AFTER_SUCCESS";
export const HOTEL_UPDATE_ADMIN_FAIL = "HOTEL_UPDATE_ADMIN_FAIL";

export const HOTEL_DELETE_ADMIN_REQUEST = "HOTEL_DELETE_ADMIN_REQUEST";
export const HOTEL_DELETE_ADMIN_SUCCESS = "HOTEL_DELETE_ADMIN_SUCCESS";
export const HOTEL_DELETE_ADMIN_AFTER_SUCCESS = "HOTEL_DELETE_ADMIN_AFTER_SUCCESS";
export const HOTEL_DELETE_ADMIN_FAIL = "HOTEL_DELETE_ADMIN_FAIL";

export const HOTEL_LIST_CUSTOMER_REQUEST = "HOTEL_LIST_CUSTOMER_REQUEST";
export const HOTEL_LIST_CUSTOMER_SUCCESS = "HOTEL_LIST_CUSTOMER_SUCCESS";
export const HOTEL_LIST_CUSTOMER_AFTER_SUCCESS = "HOTEL_LIST_CUSTOMER_AFTER_SUCCESS";
export const HOTEL_LIST_CUSTOMER_FAIL = "HOTEL_LIST_CUSTOMER_FAIL";
