export const ROOM_LIST_ADMIN_REQUEST = "ROOM_LIST_ADMIN_REQUEST";
export const ROOM_LIST_ADMIN_SUCCESS = "ROOM_LIST_ADMIN_SUCCESS";
export const ROOM_LIST_ADMIN_AFTER_SUCCESS = "ROOM_LIST_ADMIN_AFTER_SUCCESS";
export const ROOM_LIST_ADMIN_FAIL = "ROOM_LIST_ADMIN_FAIL";

export const ROOM_CREATE_ADMIN_REQUEST = "ROOM_CREATE_ADMIN_REQUEST";
export const ROOM_CREATE_ADMIN_SUCCESS = "ROOM_CREATE_ADMIN_SUCCESS";
export const ROOM_CREATE_ADMIN_AFTER_SUCCESS = "ROOM_CREATE_ADMIN_AFTER_SUCCESS";
export const ROOM_CREATE_ADMIN_FAIL = "ROOM_CREATE_ADMIN_FAIL";

export const ROOM_UPDATE_ADMIN_REQUEST = "ROOM_UPDATE_ADMIN_REQUEST";
export const ROOM_UPDATE_ADMIN_SUCCESS = "ROOM_UPDATE_ADMIN_SUCCESS";
export const ROOM_UPDATE_ADMIN_AFTER_SUCCESS = "ROOM_UPDATE_ADMIN_AFTER_SUCCESS";
export const ROOM_UPDATE_ADMIN_FAIL = "ROOM_UPDATE_ADMIN_FAIL";

export const ROOM_DELETE_ADMIN_REQUEST = "ROOM_DELETE_ADMIN_REQUEST";
export const ROOM_DELETE_ADMIN_SUCCESS = "ROOM_DELETE_ADMIN_SUCCESS";
export const ROOM_DELETE_ADMIN_AFTER_SUCCESS = "ROOM_DELETE_ADMIN_AFTER_SUCCESS";
export const ROOM_DELETE_ADMIN_FAIL = "ROOM_DELETE_ADMIN_FAIL";

export const ROOM_LIST_CUSTOMER_REQUEST = "ROOM_LIST_CUSTOMER_REQUEST";
export const ROOM_LIST_CUSTOMER_SUCCESS = "ROOM_LIST_CUSTOMER_SUCCESS";
export const ROOM_LIST_CUSTOMER_AFTER_SUCCESS = "ROOM_LIST_CUSTOMER_AFTER_SUCCESS";
export const ROOM_LIST_CUSTOMER_FAIL = "ROOM_LIST_CUSTOMER_FAIL";
