export const TRANSPORT_LIST_FOR_CUSTOMER_REQUEST = "TRANSPORT_LIST_FOR_CUSTOMER_REQUEST";
export const TRANSPORT_LIST_FOR_CUSTOMER_SUCCESS = "TRANSPORT_LIST_FOR_CUSTOMER_SUCCESS";
export const TRANSPORT_LIST_FOR_CUSTOMER_AFTER_SUCCESS = "TRANSPORT_LIST_FOR_CUSTOMER_AFTER_SUCCESS";
export const TRANSPORT_LIST_FOR_CUSTOMER_FAIL = "TRANSPORT_LIST_FOR_CUSTOMER_FAIL";

export const TRANSPORT_LIST_FOR_ADMIN_REQUEST = "TRANSPORT_LIST_FOR_ADMIN_REQUEST";
export const TRANSPORT_LIST_FOR_ADMIN_SUCCESS = "TRANSPORT_LIST_FOR_ADMIN_SUCCESS";
export const TRANSPORT_LIST_FOR_ADMIN_AFTER_SUCCESS = "TRANSPORT_LIST_FOR_ADMIN_AFTER_SUCCESS";
export const TRANSPORT_LIST_FOR_ADMIN_FAIL = "TRANSPORT_LIST_FOR_ADMIN_FAIL";

export const TRANSPORT_CREATE_REQUEST = "TRANSPORT_CREATE_REQUEST";
export const TRANSPORT_CREATE_SUCCESS = "TRANSPORT_CREATE_SUCCESS";
export const TRANSPORT_CREATE_AFTER_SUCCESS = "TRANSPORT_CREATE_AFTER_SUCCESS";
export const TRANSPORT_CREATE_FAIL = "TRANSPORT_CREATE_FAIL";

export const TRANSPORT_UPDATE_BY_ADMIN_REQUEST = "TRANSPORT_UPDATE_BY_ADMIN_REQUEST";
export const TRANSPORT_UPDATE_BY_ADMIN_SUCCESS = "TRANSPORT_UPDATE_BY_ADMIN_SUCCESS";
export const TRANSPORT_UPDATE_BY_ADMIN_AFTER_SUCCESS = "TRANSPORT_UPDATE_BY_ADMIN_AFTER_SUCCESS";
export const TRANSPORT_UPDATE_BY_ADMIN_FAIL = "TRANSPORT_UPDATE_BY_ADMIN_FAIL";

export const TRANSPORT_DELETE_BY_ADMIN_REQUEST = "TRANSPORT_DELETE_BY_ADMIN_REQUEST";
export const TRANSPORT_DELETE_BY_ADMIN_SUCCESS = "TRANSPORT_DELETE_BY_ADMIN_SUCCESS";
export const TRANSPORT_DELETE_BY_ADMIN_AFTER_SUCCESS = "TRANSPORT_DELETE_BY_ADMIN_AFTER_SUCCESS";
export const TRANSPORT_DELETE_BY_ADMIN_FAIL = "TRANSPORT_DELETE_BY_ADMIN_FAIL";
