export const TOUR_GUIDE_ADD_REQUEST = "TOUR_GUIDE_ADD_REQUEST";
export const TOUR_GUIDE_ADD_SUCCESS = "TOUR_GUIDE_ADD_SUCCESS";
export const TOUR_GUIDE_ADD_AFTER_SUCCESS = "TOUR_GUIDE_ADD_AFTER_SUCCESS";
export const TOUR_GUIDE_ADD_FAIL = "TOUR_GUIDE_ADD_FAIL";

export const TOUR_GUIDE_VIEW_REQUEST = "TOUR_GUIDE_VIEW_REQUEST";
export const TOUR_GUIDE_VIEW_SUCCESS = "TOUR_GUIDE_VIEW_SUCCESS";
export const TOUR_GUIDE_VIEW_AFTER_SUCCESS = "TOUR_GUIDE_VIEW_AFTER_SUCCESS";
export const TOUR_GUIDE_VIEW_FAIL = "TOUR_GUIDE_VIEW_FAIL";

export const TOUR_GUIDE_CUSTOMER_VIEW_REQUEST = "TOUR_GUIDE_CUSTOMER_VIEW_REQUEST";
export const TOUR_GUIDE_CUSTOMER_VIEW_SUCCESS = "TOUR_GUIDE_CUSTOMER_VIEW_SUCCESS";
export const TOUR_GUIDE_CUSTOMER_VIEW_AFTER_SUCCESS = "TOUR_GUIDE_VIEW_AFTER_SUCCESS";
export const TOUR_GUIDE_CUSTOMER_VIEW_FAIL = "TOUR_GUIDE_CUSTOMER_VIEW_FAIL";

export const TOUR_GUIDE_UPDATE_REQUEST = "TOUR_GUIDE_UPDATE_REQUEST";
export const TOUR_GUIDE_UPDATE_SUCCESS = "TOUR_GUIDE_UPDATE_SUCCESS";
export const TOUR_GUIDE_UPDATE_AFTER_SUCCESS = "TOUR_GUIDE_UPDATE_AFTER_SUCCESS";
export const TOUR_GUIDE_UPDATE_FAIL = "TOUR_GUIDE_UPDATE_FAIL";

export const TOUR_GUIDE_DELETE_REQUEST = "TOUR_GUIDE_DELETE_REQUEST";
export const TOUR_GUIDE_DELETE_SUCCESS = "TOUR_GUIDE_DELETE_SUCCESS";
export const TOUR_GUIDE_DELETE_AFTER_SUCCESS = "TOUR_GUIDE_DELETE_AFTER_SUCCESS";
export const TOUR_GUIDE_DELETE_FAIL = "TOUR_GUIDE_DELETE_FAIL";
